version: '3'
volumes:
  dates:
services:
  db:
    image: postgres:9.6
    volumes:
      # Data volume
      - dates:/var/lib/postgressql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    image: nginx:1.13
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      # Reverse proxy config
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  app:
    image: python:3.6
    volumes:
      # App
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
